
services:
  telegram-authentik-proxy:
    build: .
    container_name: telegram-authentik-proxy
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TELEGRAM_BOT_TOKEN="your_bot_token"
      - TELEGRAM_BOT_ID="your_bot_id"
      - CALLBACK_URL="https://your-domain.com/telegram/callback"
      - AUTHENTIK_REDIRECT="https://auth.your-domain.com/"
    volumes:
      - ./logs:/app/logs
